[package]
name = "user/roblox-rojo-wally-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
React = "jsdotlua/react@*"
ReactRoblox = "jsdotlua/react-roblox@*"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@*"

[dev-dependencies]
TestEZ = "roblox/testez@*"